attempt to use dockers for pre-compiled vtk and itk libs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,17 +18,6 @@ matrix:
       compiler: gcc
       env: COMPILER='g++' BUILD_TYPE='Release'
 
-cache:
-  directories:
-    - '${TRAVIS_BUILD_DIR}/deps/itk'
-    - '${TRAVIS_BUILD_DIR}/deps/vtk'
-
-before_cache:
-  - rm -r ${TRAVIS_BUILD_DIR}/deps/itk/build
-  - rm -r ${TRAVIS_BUILD_DIR}/deps/itk/src
-  - rm -r ${TRAVIS_BUILD_DIR}/deps/vtk/build
-  - rm -r ${TRAVIS_BUILD_DIR}/deps/vtk/src
-
 install:
   - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
   - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
@@ -46,17 +35,17 @@ install:
       sudo apt-get install libhdf5-dev
       sudo apt-get install libeigen3-dev
       sudo apt-get install libqt4-opengl-dev
-      sudo apt-get install libvtk7-dev
-      #docker pull itisfoundation/iseg-bionic-vtk:latest
-      #docker create --name vtklatest itisfoundation/iseg-bionic-vtk:latest bash
-      #docker cp vtklatest:/work ${TRAVIS_BUILD_DIR}/deps/vtk
+      #sudo apt-get install libvtk7-dev
+      docker pull itisfoundation/iseg-ubuntu-vtk:8.2
+      docker create --name vtkcontainer itisfoundation/iseg-ubuntu-vtk:8.2 bash
+      docker cp vtkcontainer:/work ${TRAVIS_BUILD_DIR}/deps/vtk
       #sudo apt-get install libinsighttoolkit4-dev
-      #docker pull itisfoundation/iseg-bionic-itk:latest
-      #docker create --name itklatest itisfoundation/iseg-bionic-itk:latest bash
-      #docker cp itklatest:/work ${TRAVIS_BUILD_DIR}/deps/itk
-      ITK_URL="http://downloads.sourceforge.net/project/itk/itk/4.13/InsightToolkit-4.13.1.tar.gz"
+      docker pull itisfoundation/iseg-ubuntu-itk:4.13
+      docker create --name itkcontainer itisfoundation/iseg-ubuntu-itk:4.13 bash
+      docker cp itkcontainer:/work ${TRAVIS_BUILD_DIR}/deps/itk
+      #ITK_URL="http://downloads.sourceforge.net/project/itk/itk/4.13/InsightToolkit-4.13.1.tar.gz"
       #ITK_URL="https://github.com/InsightSoftwareConsortium/ITK/releases/download/v5.0.0/InsightToolkit-5.0.0.tar.gz"
-      test -d ${DEPS_DIR}/itk/lib || (mkdir -p itk/src && travis_retry wget --no-check-certificate --quiet -O - ${ITK_URL} | tar --strip-components=1 -xz -C itk/src && mkdir itk/build && cd itk/build && cmake ../src -DCMAKE_INSTALL_PREFIX=$PWD/.. -DModule_ITKReview=ON -DCMAKE_RULE_MESSAGES=OFF && make -j2 && make install && cd ${DEPS_DIR})
+      #test -d ${DEPS_DIR}/itk/lib || (mkdir -p itk/src && travis_retry wget --no-check-certificate --quiet -O - ${ITK_URL} | tar --strip-components=1 -xz -C itk/src && mkdir itk/build && cd itk/build && cmake ../src -DCMAKE_INSTALL_PREFIX=$PWD/.. -DModule_ITKReview=ON -DCMAKE_RULE_MESSAGES=OFF && make -j2 && make install && cd ${DEPS_DIR})
 
     elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
       which cmake || brew install cmake
@@ -81,7 +70,7 @@ before_script:
   - cd ${TRAVIS_BUILD_DIR}
   - |
     if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
-      cmake -H. -BCIBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DHDF5_ROOT=/usr -DITK_DIR=`ls -d -1 ${DEPS_DIR}/itk/lib/cmake/ITK*` -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt4 -Wdev
+      cmake -H. -BCIBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DHDF5_ROOT=/usr -DVTK_DIR=`ls -d -1 ${DEPS_DIR}/vtk/lib/cmake/vtk*` -DITK_DIR=`ls -d -1 ${DEPS_DIR}/itk/lib/cmake/ITK*` -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt4 -Wdev
     elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
       cmake -H. -BCIBuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBOOST_ROOT=/usr/local/opt/boost -DHDF5_ROOT=/usr/local/opt/hdf5 -DVTK_DIR=`ls -d -1 ${DEPS_DIR}/vtk/lib/cmake/vtk*` -DITK_DIR=`ls -d -1 ${DEPS_DIR}/itk/lib/cmake/ITK*` -DQT_QMAKE_EXECUTABLE=/usr/local/bin/qmake -Wdev
     fi
